local_backend: true
backend:
  name: git-gateway
  branch: main

media_folder: "src/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "reviews"
    label: "Reviews"
    label_singular: "Review"
    folder: "src/reviews"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Game title", name: "title", widget: "string", required: true }
      - { label: "Author", name: "author", widget: "string", required: true }
      - label: "Genre"
        name: "meta"
        widget: "select"
        multiple: true
        options: ["Action", "RPG", "Soulslike", "Open-World", "Racing", "Adventure", "Shooter", "Strategy", "Simulation",
          "Sports", "Puzzle", "Horror", "Platformer", "Fighting", "MMO", "Stealth", "Survival", "Rhythm", "Visual Novel", "Party", "Educational"]
        required: true
      - label: "Platform"
        name: "platform"
        widget: "select"
        multiple: true
        options: ["PC", "PS5", "XBOX Series X/S", "Nintendo Switch 2", "PS4", "XBOX One", "Nintendo Switch","PS3", "XBOX 360", "Android", "IOS"]
        required: true
      - { label: "Cover image", name: "cover_image", widget: "image", required: true }
      - { label: "Publish date", name: "date", widget: "datetime", required: true }
      - { label: "Short excerpt (shown on cards)", name: "excerpt", widget: "text", required: true }
      - { label: "Review body (hook + story)", name: "body", widget: "markdown", required: true }
      - { label: "Pros", name: "pros", widget: "list", required: true }
      - { label: "Cons", name: "cons", widget: "list", required: true }
      - { label: "Rating", name: "cta", widget: "string", required: true }
  - name: "news"
    label: "News"
    label_singular: "News item"
    folder: "src/news"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish date", name: "date", widget: "datetime", required: true }
      - { label: "Short excerpt (shown on cards)", name: "excerpt", widget: "text", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - name: "articles"
    label: "Articles"
    label_singular: "Article"
    folder: "src/articles"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish date", name: "date", widget: "datetime", required: true }
      - { label: "Short excerpt (shown on cards)", name: "excerpt", widget: "text", required: true }
      - { label: "Body", name: "body", widget: "markdown", required: true }